import type { Lens } from './types'

// Sample data structure - this will be replaced with actual JSON data
export const sampleLenses: Lens[] = [
  {
    id: '1',
    name: 'Aviator Classic',
    brand: 'Ray-Ban',
    price: 4500,
    category: 'sol',
    gender: 'unisex',
    color: 'Dorado',
    material: 'Metal',
    images: ['/lentes/rayban-aviator-1.jpg'],
    isFeatured: true,
    isNew: true,
  },
  {
    id: '2',
    name: 'Wayfarer Original',
    brand: 'Ray-Ban',
    price: 3800,
    category: 'sol',
    gender: 'unisex',
    color: 'Negro',
    material: 'Acetato',
    images: ['/lentes/rayban-wayfarer-1.jpg'],
    isFeatured: true,
  },
  {
    id: '3',
    name: 'GG Oversized',
    brand: 'Gucci',
    price: 8500,
    category: 'sol',
    gender: 'mujer',
    color: 'Carey',
    material: 'Acetato',
    images: ['/lentes/gucci-oversized-1.jpg'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Cat Eye Elegance',
    brand: 'Tom Ford',
    price: 7200,
    category: 'sol',
    gender: 'mujer',
    color: 'Negro',
    material: 'Acetato',
    images: ['/lentes/tomford-cateye-1.jpg'],
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Round Metal',
    brand: 'Oliver Peoples',
    price: 6800,
    category: 'aumento',
    gender: 'unisex',
    color: 'Plata',
    material: 'Titanio',
    images: ['/lentes/oliver-round-1.jpg'],
  },
  {
    id: '6',
    name: 'Clubmaster',
    brand: 'Ray-Ban',
    price: 4200,
    category: 'sol',
    gender: 'unisex',
    color: 'Carey/Dorado',
    material: 'Acetato/Metal',
    images: ['/lentes/rayban-clubmaster-1.jpg'],
    isNew: true,
  },
  {
    id: '7',
    name: 'Square Frame',
    brand: 'Prada',
    price: 5900,
    category: 'aumento',
    gender: 'hombre',
    color: 'Negro Mate',
    material: 'Acetato',
    images: ['/lentes/prada-square-1.jpg'],
  },
  {
    id: '8',
    name: 'Wire Frame Slim',
    brand: 'Saint Laurent',
    price: 6500,
    category: 'sol',
    gender: 'mujer',
    color: 'Dorado',
    material: 'Metal',
    images: ['/lentes/sl-wire-1.jpg'],
    isFeatured: true,
  },
  {
    id: '9',
    name: 'Sport Performance',
    brand: 'Oakley',
    price: 3500,
    category: 'sol',
    gender: 'hombre',
    color: 'Negro/Rojo',
    material: 'O-Matter',
    images: ['/lentes/oakley-sport-1.jpg'],
  },
  {
    id: '10',
    name: 'Rectangular Classic',
    brand: 'Versace',
    price: 5400,
    category: 'aumento',
    gender: 'hombre',
    color: 'Habana',
    material: 'Acetato',
    images: ['/lentes/versace-rect-1.jpg'],
  },
  {
    id: '11',
    name: 'Butterfly Glamour',
    brand: 'Chanel',
    price: 9200,
    category: 'sol',
    gender: 'mujer',
    color: 'Negro/Perla',
    material: 'Acetato',
    images: ['/lentes/chanel-butterfly-1.jpg'],
    isNew: true,
  },
  {
    id: '12',
    name: 'Geometric Modern',
    brand: 'Dior',
    price: 7800,
    category: 'sol',
    gender: 'mujer',
    color: 'Rosa Gold',
    material: 'Metal',
    images: ['/lentes/dior-geometric-1.jpg'],
    isFeatured: true,
  },
]

export const brands = [
  'Ray-Ban',
  'Gucci',
  'Tom Ford',
  'Oliver Peoples',
  'Prada',
  'Saint Laurent',
  'Oakley',
  'Versace',
  'Chanel',
  'Dior',
]

export const categories = [
  { id: 'sol', name: 'Lentes de Sol', icon: 'sun' },
  { id: 'aumento', name: 'Lentes de Aumento', icon: 'glasses' },
]

export const genderOptions = [
  { id: 'unisex', name: 'Unisex' },
  { id: 'hombre', name: 'Hombre' },
  { id: 'mujer', name: 'Mujer' },
]
